### PR TITLE
Feat/tib endpoint integration

### PR DESCRIPTION
**Pull request by Pooya-Oladazimi**
Changes:
* Added TIB endpoint for all Stories 
* Added Two new Stories for NFDI4chem and DataPlant collection in TIB. Target Widgets:
     * AutoComplete
     * SearchBar
     * SearchResultList

### CODE REVIEW

**Review by jusa3 — COMMENTED** [review]
If you like, you can add a comment for the Storybook documentation [here](https://github.com/nfdi4health/semlookp-widgets/blob/main/src/utils/types.ts#L36C4-L42C8)

Where did you add the stories? Can't see any changes.

The package-lock.json file does not seem to be up to date...

**Comment by Pooya-Oladazimi** [comment]
@jusa3 
Sorry. Forgot to push the story-related commit. Doc and package-lock updates are also added.

**Comment by jusa3** [comment]
Still some dependency issues:
https://github.com/nfdi4health/semlookp-widgets/actions/runs/8540906351/job/23399022724#step:4:10

**Comment by Pooya-Oladazimi** [comment]
@jusa3 
I think it is fine now as checks have passed. My lock was a bit messed up since I did some try-and-error for those peer dependencies. I hope it is fine now. Sorry for the confusion.

**Review by jusa3 — APPROVED** [review]

**Pull request merged**
